#!/usr/bin/env python3

import argparse
import base64
import json
from pathlib import Path

import pandas as pd


def b64_png(path: str) -> str:
    data = Path(path).read_bytes()
    return base64.b64encode(data).decode("ascii")


def html_table(df: pd.DataFrame, max_rows: int = 25) -> str:
    if len(df) > max_rows:
        df = df.head(max_rows)
    return df.to_html(index=False, escape=True)


def main() -> None:
    ap = argparse.ArgumentParser(description="Build a simple HTML report")
    ap.add_argument("--pca-info",            required=True)
    ap.add_argument("--clusters",            required=True)
    ap.add_argument("--k-sweep",             required=True)
    ap.add_argument("--selected-metrics",    required=True)
    ap.add_argument("--umap-embedding",      required=True)
    ap.add_argument("--tsne-embedding",      required=True)
    ap.add_argument("--umap-png",            required=True)
    ap.add_argument("--tsne-png",            required=True)
    ap.add_argument("--elbow-png",           required=True)
    ap.add_argument("--silhouette-png",      required=True)
    ap.add_argument("--davies-bouldin-png",  required=True)
    ap.add_argument("--pca-cluster-png",     required=True)
    ap.add_argument("--out",                 required=True)
    args = ap.parse_args()

    pca_info = json.loads(Path(args.pca_info).read_text())
    selected = json.loads(Path(args.selected_metrics).read_text())

    # FIX: clustering.py scrive CSV (sep=","), non TSV
    clusters_df = pd.read_csv(args.clusters, sep=",")
    counts = clusters_df["cluster"].value_counts().sort_index().reset_index()
    counts.columns = ["cluster", "n_samples"]

    k_df    = pd.read_csv(args.k_sweep, sep=",")
    umap_df = pd.read_csv(args.umap_embedding, sep="\t")
    tsne_df = pd.read_csv(args.tsne_embedding, sep="\t")

    umap_b64       = b64_png(args.umap_png)
    tsne_b64       = b64_png(args.tsne_png)
    elbow_b64      = b64_png(args.elbow_png)
    sil_b64        = b64_png(args.silhouette_png)
    db_b64         = b64_png(args.davies_bouldin_png)
    pca_cluster_b64 = b64_png(args.pca_cluster_png)

    html = f"""<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>VCF clustering report</title>
  <style>
    body {{ font-family: Arial, sans-serif; margin: 24px; }}
    h1, h2 {{ margin-bottom: 0.3rem; }}
    .meta {{ color: #555; margin-top: 0.2rem; }}
    .card {{ border: 1px solid #ddd; border-radius: 12px; padding: 16px; margin: 16px 0; }}
    table {{ border-collapse: collapse; width: 100%; }}
    th, td {{ border: 1px solid #ddd; padding: 6px 8px; font-size: 14px; }}
    th {{ background: #f6f6f6; }}
    img {{ max-width: 100%; height: auto; }}
    code {{ background: #f6f6f6; padding: 2px 4px; border-radius: 4px; }}
  </style>
</head>
<body>

<h1>VCF clustering report</h1>
<div class="meta">Generated by Nextflow pipeline</div>

<div class="card">
  <h2>PCA / features</h2>
  <pre>{json.dumps(pca_info, indent=2)}</pre>
</div>

<div class="card">
  <h2>Clustering summary</h2>
  <h3>Cluster sizes</h3>
  {html_table(counts)}
  <h3>Selected clustering metrics</h3>
  <pre>{json.dumps(selected, indent=2)}</pre>
</div>

<div class="card">
  <h2>KMeans k-sweep</h2>
  {html_table(k_df, max_rows=15)}
</div>

<div class="card">
  <h2>Cluster metrics (k-sweep plots)</h2>
  <h3>Elbow (inertia)</h3>
  <img src="data:image/png;base64,{elbow_b64}" alt="elbow" />
  <h3>Silhouette</h3>
  <img src="data:image/png;base64,{sil_b64}" alt="silhouette" />
  <h3>Davies-Bouldin</h3>
  <img src="data:image/png;base64,{db_b64}" alt="davies_bouldin" />
</div>

<div class="card">
  <h2>PCA colored by cluster</h2>
  <img src="data:image/png;base64,{pca_cluster_b64}" alt="pca_cluster" />
</div>

<div class="card">
  <h2>Embeddings</h2>
  <h3>UMAP</h3>
  <img src="data:image/png;base64,{umap_b64}" alt="umap" />
  <h4>First rows (coordinates)</h4>
  {html_table(umap_df, max_rows=15)}
  <h3>t-SNE</h3>
  <img src="data:image/png;base64,{tsne_b64}" alt="tsne" />
  <h4>First rows (coordinates)</h4>
  {html_table(tsne_df, max_rows=15)}
</div>

</body>
</html>
"""

    Path(args.out).write_text(html)


if __name__ == "__main__":
    main()
